### ISSUE TITLE
HTML Bugs

### ISSUE THREAD

**Issue by jpere039** [badavis/183Project#3]
Template.html:
About button and Project Name buttons are non functional
Tab name is still "Starter template for bootstrap"
On contact page clicking LinkedIn profiles renders the error:

Not Found

The requested URL /www.linkedin.com/in/michaellacolla/en was not found on this server.
Apache/2.2.15 (CentOS) Server at localhost Port 2204

**Comment by emarel** [comment]
Web site pages are fixed, Just need to push. I also need pictures from both
Zach and Ben. For the about section I will complete it with what we write
for the written portion.

**Comment by jpere039** [comment]
Tested with commit 991c5b51822ad94a60344ccca35c6aee3e7a5bc6 and problem persists

**Comment by jpere039** [comment]
Errors:
GET http://localhost:2204/js/ie-emulation-modes-warning.js [HTTP/1.1 404 Not Found 6ms]
GET http://localhost:2204/js/ie10-viewport-bug-workaround.js [HTTP/1.1 404 Not Found 7ms]
GET http://localhost:2204/dist/js/bootstrap.min.js [HTTP/1.1 404 Not Found 5ms]
GET http://localhost:2204/assets/js/docs.min.js [HTTP/1.1 404 Not Found 5ms]
GET http://localhost:2204/assets/js/ie10-viewport-bug-workaround.js [HTTP/1.1 404 Not Found 8ms]
GET http://localhost:2204/js/ie-emulation-modes-warning.js [HTTP/1.1 404 Not Found 2ms]
GET http://localhost:2204/js/ie10-viewport-bug-workaround.js [HTTP/1.1 404 Not Found 2ms]
GET http://localhost:2204/img/uptodate.png [HTTP/1.1 404 Not Found 2ms]
GET http://localhost:2204/img/outofdate.png [HTTP/1.1 404 Not Found 3ms]
GET http://localhost:2204/dist/js/bootstrap.min.js [HTTP/1.1 404 Not Found 2ms]
GET http://localhost:2204/fonts/glyphicons-halflings-regular.woff [HTTP/1.1 404 Not Found 3ms]
downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:normal stretch:normal src index:1): status=2147746065 source: http://localhost:2204/fonts/glyphicons-halflings-regular.woff bootstrap.min.css:5:2928
GET http://localhost:2204/fonts/glyphicons-halflings-regular.ttf [HTTP/1.1 404 Not Found 2ms]
GET http://localhost:2204/assets/js/docs.min.js [HTTP/1.1 404 Not Found 3ms]
downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:normal stretch:normal src index:2): status=2147746065 source: http://localhost:2204/fonts/glyphicons-halflings-regular.ttf bootstrap.min.css:5:2928
GET http://localhost:2204/assets/js/ie10-viewport-bug-workaround.js [HTTP/1.1 404 Not Found 1ms]

**Comment by jpere039** [comment]
New Errors:

GET http://localhost:2204/js/ie-emulation-modes-warning.js [HTTP/1.1 404 Not Found 17ms]
GET http://localhost:2204/js/ie10-viewport-bug-workaround.js [HTTP/1.1 404 Not Found 5ms]
GET http://localhost:2204/dist/js/bootstrap.min.js [HTTP/1.1 404 Not Found 14ms]
GET http://localhost:2204/assets/js/docs.min.js [HTTP/1.1 404 Not Found 7ms]
GET http://localhost:2204/assets/js/ie10-viewport-bug-workaround.js [HTTP/1.1 404 Not Found 11ms]
GET http://localhost:2204/js/ie-emulation-modes-warning.js [HTTP/1.1 404 Not Found 4ms]
GET http://localhost:2204/js/ie10-viewport-bug-workaround.js [HTTP/1.1 404 Not Found 3ms]
GET http://localhost:2204/dist/js/bootstrap.min.js [HTTP/1.1 404 Not Found 6ms]
GET http://localhost:2204/assets/js/docs.min.js [HTTP/1.1 404 Not Found 2ms]
GET http://localhost:2204/assets/js/ie10-viewport-bug-workaround.js [HTTP/1.1 404 Not Found 2ms]
GET http://localhost:2204/sccm/comment_current.log [HTTP/1.1 404 Not Found 1ms]

**Comment by jpere039** [comment]
Fixed
